# Generated by Django 5.2.6 on 2025-10-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_identification_approvallink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalLink',
        ),
    ]
