# Generated by Django 5.2 on 2025-10-01 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con esta identificación'}, help_text='Número de identificación del usuario', max_length=20, unique=True, verbose_name='Número de Identificación'),
        ),
        migrations.CreateModel(
            name='ApprovalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Aprobar'), ('reject', 'Rechazar')], max_length=10, verbose_name='Acción')),
                ('token_hash', models.CharField(help_text='Hash único del token para validación', max_length=64, unique=True, verbose_name='Hash del Token')),
                ('used_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se usó el enlace', null=True, verbose_name='Usado en')),
                ('expires_at', models.DateTimeField(help_text='Fecha y hora de expiración del enlace', verbose_name='Expira en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_links', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Enlace de Aprobación',
                'verbose_name_plural': 'Enlaces de Aprobación',
                'db_table': 'users_approval_link',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='users_appro_token_h_409bce_idx'), models.Index(fields=['user', 'action'], name='users_appro_user_id_1da152_idx'), models.Index(fields=['expires_at'], name='users_appro_expires_2eb7c2_idx')],
            },
        ),
    ]
