# Generated by Django 5.2.6 on 2025-10-01 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_identification_approvallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_password_reset',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='users_passw_token_h_b6b4b5_idx'), models.Index(fields=['user'], name='users_passw_user_id_b31a75_idx'), models.Index(fields=['expires_at'], name='users_passw_expires_d81899_idx')],
            },
        ),
    ]
