# Generated by Django 4.2.25 on 2025-11-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_passwordreset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Administrador"), ("user", "Usuario")],
                default="user",
                help_text="Rol del usuario en el sistema de gestión financiera",
                max_length=10,
            ),
        ),
    ]
