# Generated by Django 4.2.25 on 2025-11-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalLink',
        ),
    ]
