# Generated by Django 4.2.25 on 2025-12-08 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit_cards', '0002_add_totals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
