# Generated by Django 4.2.16 on 2025-11-22 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la meta de ahorro', max_length=100, verbose_name='Nombre de la meta')),
                ('target_ammount', models.IntegerField(help_text='Monto objetivo de la meta de ahorro', verbose_name='Monto objetivo')),
                ('saved_ammount', models.IntegerField(help_text='Monto actualmente ahorrado hacia la meta', verbose_name='Monto ahorrado')),
                ('date', models.DateField(help_text='Fecha de la meta de ahorro', verbose_name='Fecha')),
                ('description', models.TextField(blank=True, help_text='Descripción adicional de la meta de ahorro (opcional)', null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la transacción')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('user', models.ForeignKey(help_text='Usuario propietario de la meta de ahorro', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
