# Generated by Django 4.2.16 on 2025-10-20 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo de la exportación', max_length=200, verbose_name='Título')),
                ('export_type', models.CharField(choices=[('monitors_data', 'Datos de Monitores'), ('attendance_data', 'Datos de Asistencia'), ('schedule_data', 'Datos de Turnos'), ('room_entries_data', 'Datos de Entradas a Salas')], help_text='Tipo de datos a exportar', max_length=30, verbose_name='Tipo de exportación')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], help_text='Formato de archivo de exportación', max_length=10, verbose_name='Formato')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', help_text='Estado actual del trabajo de exportación', max_length=15, verbose_name='Estado')),
                ('start_date', models.DateField(blank=True, help_text='Fecha inicial del período a exportar', null=True, verbose_name='Fecha inicial')),
                ('end_date', models.DateField(blank=True, help_text='Fecha final del período a exportar', null=True, verbose_name='Fecha final')),
                ('monitor_ids', models.JSONField(blank=True, help_text='Lista de IDs de monitores específicos a exportar', null=True, verbose_name='IDs de Monitores')),
                ('file', models.FileField(blank=True, help_text='Archivo de exportación generado', null=True, upload_to='exports/', verbose_name='Archivo generado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Fecha y hora de finalización del trabajo', null=True, verbose_name='Completado en')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si el trabajo falló', verbose_name='Mensaje de error')),
                ('file_size', models.BigIntegerField(blank=True, help_text='Tamaño del archivo generado en bytes', null=True, verbose_name='Tamaño del archivo')),
                ('requested_by', models.ForeignKey(help_text='Usuario que solicitó la exportación', on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Trabajo de Exportación',
                'verbose_name_plural': 'Trabajos de Exportación',
                'db_table': 'export_exportjob',
                'ordering': ['-created_at'],
            },
        ),
    ]
