# Generated by Django 5.2.5 on 2025-09-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo del reporte', max_length=200, verbose_name='Título')),
                ('report_type', models.CharField(choices=[('hours_summary', 'Resumen de horas'), ('attendance', 'Asistencia'), ('equipment_status', 'Estado de equipos'), ('incapacity', 'Incapacidades')], help_text='Tipo de información incluida en el reporte', max_length=30, verbose_name='Tipo de reporte')),
                ('start_date', models.DateField(help_text='Fecha inicial del período del reporte', verbose_name='Fecha inicial')),
                ('end_date', models.DateField(help_text='Fecha final del período del reporte', verbose_name='Fecha final')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], default='pdf', help_text='Formato de exportación del reporte', max_length=10, verbose_name='Formato')),
                ('file', models.FileField(blank=True, help_text='Archivo del reporte generado', null=True, upload_to='reports/', verbose_name='Archivo generado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Usuario que generó el reporte', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('user_filter', models.ForeignKey(blank=True, help_text='Filtrar reporte para un usuario específico (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filtered_reports', to=settings.AUTH_USER_MODEL, verbose_name='Filtrado por usuario')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
    ]
