# Generated by Django 4.2.16 on 2025-11-16 03:07

import categories.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría (ej: Comida, Salario)', max_length=100)),
                ('type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto')], help_text='Tipo de categoría: ingreso o gasto', max_length=10)),
                ('color', models.CharField(default='#3B82F6', help_text='Color en formato hexadecimal (ej: #FF5733)', max_length=7, validators=[categories.models.validate_hex_color, categories.models.validate_color_contrast])),
                ('icon', models.CharField(choices=[('fa-shopping-cart', 'Carrito de compras'), ('fa-utensils', 'Comida'), ('fa-home', 'Casa'), ('fa-car', 'Transporte'), ('fa-heart', 'Salud'), ('fa-graduation-cap', 'Educación'), ('fa-film', 'Entretenimiento'), ('fa-tshirt', 'Ropa'), ('fa-plane', 'Viajes'), ('fa-mobile-alt', 'Teléfono'), ('fa-wifi', 'Internet'), ('fa-bolt', 'Servicios públicos'), ('fa-money-bill-wave', 'Salario'), ('fa-briefcase', 'Negocio'), ('fa-gift', 'Regalos'), ('fa-hand-holding-usd', 'Inversión'), ('fa-piggy-bank', 'Ahorros'), ('fa-credit-card', 'Tarjeta'), ('fa-wallet', 'Billetera'), ('fa-chart-line', 'Ingresos'), ('fa-shopping-bag', 'Compras'), ('fa-coffee', 'Café'), ('fa-dumbbell', 'Gimnasio'), ('fa-paw', 'Mascotas'), ('fa-gamepad', 'Juegos'), ('fa-book', 'Libros'), ('fa-music', 'Música'), ('fa-tools', 'Herramientas'), ('fa-paint-brush', 'Arte'), ('fa-umbrella', 'Seguros'), ('fa-medkit', 'Medicinas'), ('fa-laptop', 'Tecnología'), ('fa-tv', 'Electrónicos'), ('fa-couch', 'Muebles'), ('fa-baby', 'Bebé'), ('fa-hamburger', 'Comida rápida'), ('fa-pizza-slice', 'Pizza'), ('fa-wine-glass', 'Bebidas'), ('fa-smoking', 'Tabaco'), ('fa-tree', 'Jardín'), ('fa-bicycle', 'Bicicleta'), ('fa-bus', 'Bus'), ('fa-taxi', 'Taxi'), ('fa-gas-pump', 'Gasolina'), ('fa-parking', 'Parqueadero'), ('fa-hotel', 'Hotel'), ('fa-suitcase', 'Equipaje'), ('fa-map', 'Mapas'), ('fa-ticket-alt', 'Tickets'), ('fa-dollar-sign', 'Dinero'), ('fa-coins', 'Monedas'), ('fa-percent', 'Descuentos'), ('fa-tags', 'Etiquetas'), ('fa-star', 'Favoritos'), ('fa-question-circle', 'Otros')], default='fa-question-circle', help_text='Ícono de Font Awesome para representar la categoría', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la categoría está activa y disponible para usar')),
                ('is_default', models.BooleanField(default=False, help_text='Indica si es una categoría del sistema (no editable por usuario)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización en listas')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la categoría')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('user', models.ForeignKey(help_text='Usuario propietario de la categoría', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['user', 'type', 'is_active'], name='categories__user_id_d42513_idx'), models.Index(fields=['user', 'is_active'], name='categories__user_id_15497c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'type'), name='unique_category_per_user'),
        ),
    ]
