# Generated by Django 4.2.16 on 2025-11-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fa-shopping-cart', 'Carrito de compras'), ('fa-shopping-basket', 'Canasta de compras'), ('fa-utensils', 'Comida'), ('fa-home', 'Casa'), ('fa-car', 'Transporte'), ('fa-heart', 'Salud'), ('fa-graduation-cap', 'Educación'), ('fa-film', 'Entretenimiento'), ('fa-tshirt', 'Ropa'), ('fa-plane', 'Viajes'), ('fa-mobile-alt', 'Teléfono'), ('fa-wifi', 'Internet'), ('fa-bolt', 'Servicios públicos'), ('fa-money-bill-wave', 'Salario'), ('fa-briefcase', 'Negocio'), ('fa-gift', 'Regalos'), ('fa-hand-holding-usd', 'Inversión'), ('fa-piggy-bank', 'Ahorros'), ('fa-credit-card', 'Tarjeta'), ('fa-wallet', 'Billetera'), ('fa-chart-line', 'Ingresos'), ('fa-shopping-bag', 'Compras'), ('fa-coffee', 'Café'), ('fa-dumbbell', 'Gimnasio'), ('fa-paw', 'Mascotas'), ('fa-gamepad', 'Juegos'), ('fa-book', 'Libros'), ('fa-music', 'Música'), ('fa-tools', 'Herramientas'), ('fa-paint-brush', 'Arte'), ('fa-umbrella', 'Seguros'), ('fa-medkit', 'Medicinas'), ('fa-laptop', 'Tecnología'), ('fa-tv', 'Electrónicos'), ('fa-couch', 'Muebles'), ('fa-baby', 'Bebé'), ('fa-hamburger', 'Comida rápida'), ('fa-pizza-slice', 'Pizza'), ('fa-wine-glass', 'Bebidas'), ('fa-smoking', 'Tabaco'), ('fa-tree', 'Jardín'), ('fa-bicycle', 'Bicicleta'), ('fa-bus', 'Bus'), ('fa-taxi', 'Taxi'), ('fa-gas-pump', 'Gasolina'), ('fa-parking', 'Parqueadero'), ('fa-hotel', 'Hotel'), ('fa-suitcase', 'Equipaje'), ('fa-map', 'Mapas'), ('fa-ticket-alt', 'Tickets'), ('fa-dollar-sign', 'Dinero'), ('fa-coins', 'Monedas'), ('fa-percent', 'Descuentos'), ('fa-tags', 'Etiquetas'), ('fa-star', 'Favoritos'), ('fa-question-circle', 'Otros')], default='fa-question-circle', help_text='Ícono de Font Awesome para representar la categoría', max_length=50),
        ),
    ]
