# Generated by Django 4.2.16 on 2025-11-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="budget",
            name="unique_budget_per_category_period",
        ),
        migrations.AddField(
            model_name="budget",
            name="currency",
            field=models.CharField(
                choices=[("COP", "Pesos Colombianos"), ("USD", "Dólares"), ("EUR", "Euros")],
                default="COP",
                help_text="Moneda del presupuesto",
                max_length=3,
                verbose_name="Moneda",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                fields=("user", "category", "period", "currency"),
                name="unique_budget_per_category_period_currency",
                violation_error_message="Ya existe un presupuesto para esta categoría, período y moneda.",
            ),
        ),
    ]
