# Generated by Django 5.2.5 on 2025-09-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('room_entry', 'Entrada a sala'), ('room_exit', 'Salida de sala'), ('incapacity', 'Incapacidad registrada'), ('equipment_report', 'Reporte de equipo'), ('attendance', 'Listado de asistencia'), ('admin_verification', 'Verificación de usuario')], help_text='Tipo de notificación', max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(help_text='Título breve de la notificación', max_length=200, verbose_name='Título')),
                ('message', models.TextField(help_text='Mensaje detallado de la notificación', verbose_name='Mensaje')),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID del objeto relacionado con la notificación (ej. ID de una entrada, incapacidad, etc.)', null=True, verbose_name='ID de objeto relacionado')),
                ('read', models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída', verbose_name='Leída')),
                ('read_timestamp', models.DateTimeField(blank=True, help_text='Fecha y hora en que se leyó la notificación', null=True, verbose_name='Fecha de lectura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
