# Generated by Django 4.2.25 on 2025-10-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('room_entry', 'Entrada a sala'), ('room_exit', 'Salida de sala'), ('incapacity', 'Incapacidad registrada'), ('equipment_report', 'Reporte de equipo'), ('attendance', 'Listado de asistencia'), ('admin_verification', 'Verificación de usuario'), ('excessive_hours', 'Exceso de horas continuas'), ('conversation_message', 'Nuevo mensaje en conversación')], help_text='Tipo de notificación', max_length=30, verbose_name='Tipo'),
        ),
    ]
