# Generated by Django 5.2 on 2025-10-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Alias para compatibilidad con frontend', verbose_name='Leída (alias)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='monitor_id',
            field=models.IntegerField(blank=True, help_text='ID del monitor relacionado con la notificación', null=True, verbose_name='ID del Monitor'),
        ),
        migrations.AddField(
            model_name='notification',
            name='monitor_name',
            field=models.CharField(blank=True, help_text='Nombre del monitor relacionado con la notificación', max_length=100, verbose_name='Nombre del Monitor'),
        ),
    ]
