# Generated by Django 4.2.25 on 2025-12-08 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0007_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del recordatorio', max_length=200, verbose_name='Título')),
                ('message', models.TextField(help_text='Mensaje detallado del recordatorio', verbose_name='Mensaje')),
                ('reminder_date', models.DateField(help_text='Fecha en que se debe enviar el recordatorio', verbose_name='Fecha del recordatorio')),
                ('reminder_time', models.TimeField(help_text='Hora en que se debe enviar el recordatorio', verbose_name='Hora del recordatorio')),
                ('is_sent', models.BooleanField(default=False, help_text='Indica si el recordatorio ya fue enviado', verbose_name='Enviado')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se envió el recordatorio', null=True, verbose_name='Enviado en')),
                ('is_read', models.BooleanField(default=False, help_text='Indica si el recordatorio ha sido leído', verbose_name='Leído')),
                ('read_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se leyó el recordatorio', null=True, verbose_name='Leído en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recordatorio personalizado',
                'verbose_name_plural': 'Recordatorios personalizados',
                'ordering': ['reminder_date', 'reminder_time'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, help_text='Tipo del objeto relacionado (budget, bill, soat, custom_reminder)', max_length=50, null=True, verbose_name='Tipo de objeto relacionado'),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora programada para enviar la notificación (recordatorios)', null=True, verbose_name='Programado para'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se envió la notificación', null=True, verbose_name='Enviado en'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'Notificación general'), ('admin_verification', 'Verificación de usuario'), ('system_alert', 'Alerta del sistema'), ('user_action', 'Acción del usuario'), ('budget_warning', 'Alerta de presupuesto (80%)'), ('budget_exceeded', 'Presupuesto excedido (100%)'), ('bill_reminder', 'Recordatorio de factura'), ('soat_reminder', 'Recordatorio de SOAT'), ('month_end_reminder', 'Recordatorio de fin de mes'), ('custom_reminder', 'Recordatorio personalizado')], default='general', help_text='Tipo de notificación', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_object_id',
            field=models.IntegerField(blank=True, help_text='ID del objeto relacionado con la notificación (Budget, Bill, SOAT, etc.)', null=True, verbose_name='ID de objeto relacionado'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read'], name='notificatio_user_id_878a13_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for'], name='notificatio_schedul_cf7340_idx'),
        ),
        migrations.AddField(
            model_name='customreminder',
            name='notification',
            field=models.OneToOneField(blank=True, help_text='Notificación generada para este recordatorio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_reminder', to='notifications.notification', verbose_name='Notificación'),
        ),
        migrations.AddField(
            model_name='customreminder',
            name='user',
            field=models.ForeignKey(help_text='Usuario propietario del recordatorio', on_delete=django.db.models.deletion.CASCADE, related_name='custom_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='customreminder',
            index=models.Index(fields=['user', 'is_sent'], name='notificatio_user_id_968647_idx'),
        ),
        migrations.AddIndex(
            model_name='customreminder',
            index=models.Index(fields=['reminder_date', 'reminder_time'], name='notificatio_reminde_4ecb46_idx'),
        ),
    ]
