# Generated by Django 4.2.16 on 2025-12-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_customreminder_notification_related_object_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="dismissed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que se descartó la notificación",
                null=True,
                verbose_name="Descartada en",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_dismissed",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la notificación ha sido descartada por el usuario",
                verbose_name="Descartada",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_dismissed"], name="notificatio_user_id_c37c69_idx"
            ),
        ),
    ]
